language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
  - cd $HOME
  - git clone git://github.com/n1k0/casperjs.git
  - cd casperjs
  - git checkout tags/1.0.2
  - sudo ln -sf `pwd`/bin/casperjs /usr/local/bin/casperjs
  - cd $TRAVIS_BUILD_DIR
before_script:
  - npm install -g grunt-cli
